docker-compose -f docker/wordpres.yml up -d
- name:  test
  uses: luke142367/Docker-Lint-Action@v1.0.0
  with:
    # Paths to dockerfiles
    target: # optional, default is Dockerfile
    
    
    - name: Laravel PHPUnit
  uses: nathanheffley/laravel-phpunit-action@v0.1.0
